/* This file is automatically generated.
   This file selects the right generated file of `__stub_FUNCTION' macros
   based on the architecture being compiled for.  */

#include <bits/wordsize.h>

#if (__SIZEOF_INT__ == 4) && (__SIZEOF_LONG__ == 4) && (__SIZEOF_POINTER__ == 4) && (defined __riscv_float_abi_soft) && (!defined __riscv_float_abi_single) && (!defined __riscv_float_abi_double)
# include <gnu/stubs-ilp32.h>
#endif
#if (__SIZEOF_INT__ == 4) && (__SIZEOF_LONG__ == 4) && (__SIZEOF_POINTER__ == 4) && (!defined __riscv_float_abi_soft) && (defined __riscv_float_abi_single) && (!defined __riscv_float_abi_double)
# include <gnu/stubs-ilp32f.h>
#endif
#if (__SIZEOF_INT__ == 4) && (__SIZEOF_LONG__ == 4) && (__SIZEOF_POINTER__ == 4) && (!defined __riscv_float_abi_soft) && (!defined __riscv_float_abi_single) && (defined __riscv_float_abi_double)
# include <gnu/stubs-ilp32d.h>
#endif
#if (__SIZEOF_INT__ == 4) && (__SIZEOF_LONG__ == 8) && (__SIZEOF_POINTER__ == 8) && (defined __riscv_float_abi_soft) && (!defined __riscv_float_abi_single) && (!defined __riscv_float_abi_double)
# include <gnu/stubs-lp64.h>
#endif
#if (__SIZEOF_INT__ == 4) && (__SIZEOF_LONG__ == 8) && (__SIZEOF_POINTER__ == 8) && (!defined __riscv_float_abi_soft) && (defined __riscv_float_abi_single) && (!defined __riscv_float_abi_double)
# include <gnu/stubs-lp64f.h>
#endif
#if (__SIZEOF_INT__ == 4) && (__SIZEOF_LONG__ == 8) && (__SIZEOF_POINTER__ == 8) && (!defined __riscv_float_abi_soft) && (!defined __riscv_float_abi_single) && (defined __riscv_float_abi_double)
# include <gnu/stubs-lp64d.h>
#endif
